# serene v5.5.0
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================

base_url = "https://pooladkhay.com"
title = "MJ Pooladkhay"
description = "MJ Pooladkhay's personal website"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false # Keep this false, as it may cause issues with some styles
build_search_index = false # Keep this false, search is temporarily unsupported
generate_feeds = true # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filenames = ["feed.xml"] # "feed.xml" | "atom.xml" | "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "posts", path = "/posts", is_external = false },
  { name = "tags", path = "/tags", is_external = false },
  # { name = "about", path = "/about", is_external = false },
]
blog_section_path = "/posts"

back_link_text = "Back" # Text of the back button
force_theme = false # false | "light" | "dark"

footer_copyright = "© 2025 MJ Pooladkhay"
footer_credits = false # Whether to show "Built with zola and serene" in footer

not_found_error_text = "110010100 - not found"
not_found_recover_text = "← back home"

reaction = false # Whether to enable anonymous emoji reactions (Note: You need to set up a working api endpoint to enable this feature)
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"

display_id = false      # Whether to display your id on homepage
blog_categorized = true # Whether to categorize blog posts
blur_effect = true      # Whether to turn on blur effect on navigation bar
back_to_top = true      # Whether to show back-to-top button on post pages
