name = "pooladkhay-com"
compatibility_date = "2025-11-08"

routes = [
  { pattern = "pooladkhay.com", custom_domain = true }
]

[assets]
directory = "./public/"
not_found_handling = "404-page"

[build]
command = 'chmod +x build.sh && ./build.sh'
